disabled_rules:
  - todo
  - type_body_length
  - file_length
  # should be re-enabled
  - nesting
  # should be re-enabled
  - xctfail_message
  - identifier_name
  - function_body_length
  - trailing_comma
  - cyclomatic_complexity

analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  # - explicit_type_interface should be uncommented
  - force_unwrapping
  - implicit_return
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_string
  - contains_over_first_not_nil
  - indentation_width

excluded:
  - Carthage
  - Pods
  - .build
  - Demos/VaporDemo/.build
  - Demos/PerfectDemo/.build

force_cast: warning
force_try: warning

explicit_type_interface:
  severity: warning

line_length: 200

indentation_width:
  indentation_width: 2
  include_comments: false

child_config: ./Tests/.swiftlint_for_tests.yml
